name: Code Quality Check

on: [push]


jobs:

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace 'x' with the desired version
    
      - name: Run pylint
        run: |
          pip install pylint
          pylint main.py

